ERROR:root:Error caught: Error - # channels not specified
Traceback (most recent call last):
  File "d:\git\EncrypDecrypImage\En&deUI.py", line 74, in encrypt_decrypt_audio_file
    wave_file.setnchannels(wave_file.getnchannels())
                           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ypuku\AppData\Local\Programs\Python\Python312\Lib\wave.py", line 485, in getnchannels
    raise Error('number of channels not set')
wave.Error: number of channels not set

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\git\EncrypDecrypImage\En&deUI.py", line 73, in encrypt_decrypt_audio_file
    with wave.open(temp_file_path, 'wb') as wave_file:
  File "C:\Users\ypuku\AppData\Local\Programs\Python\Python312\Lib\wave.py", line 471, in __exit__
    self.close()
  File "C:\Users\ypuku\AppData\Local\Programs\Python\Python312\Lib\wave.py", line 583, in close
    self._ensure_header_written(0)
  File "C:\Users\ypuku\AppData\Local\Programs\Python\Python312\Lib\wave.py", line 601, in _ensure_header_written
    raise Error('# channels not specified')
wave.Error: # channels not specified
ERROR:root:Error caught: Error - # channels not specified
Traceback (most recent call last):
  File "d:\git\EncrypDecrypImage\En&deUI.py", line 74, in encrypt_decrypt_audio_file
    wave_file.setnchannels(wave_file.getnchannels())
                           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ypuku\AppData\Local\Programs\Python\Python312\Lib\wave.py", line 485, in getnchannels
    raise Error('number of channels not set')
wave.Error: number of channels not set

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\git\EncrypDecrypImage\En&deUI.py", line 73, in encrypt_decrypt_audio_file
    with wave.open(temp_file_path, 'wb') as wave_file:
  File "C:\Users\ypuku\AppData\Local\Programs\Python\Python312\Lib\wave.py", line 471, in __exit__
    self.close()
  File "C:\Users\ypuku\AppData\Local\Programs\Python\Python312\Lib\wave.py", line 583, in close
    self._ensure_header_written(0)
  File "C:\Users\ypuku\AppData\Local\Programs\Python\Python312\Lib\wave.py", line 601, in _ensure_header_written
    raise Error('# channels not specified')
wave.Error: # channels not specified
ERROR:root:Error caught: Error - # channels not specified
Traceback (most recent call last):
  File "d:\git\EncrypDecrypImage\En&deUI.py", line 74, in encrypt_decrypt_audio_file
    wave_file.setnchannels(wave_file.getnchannels())
                           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ypuku\AppData\Local\Programs\Python\Python312\Lib\wave.py", line 485, in getnchannels
    raise Error('number of channels not set')
wave.Error: number of channels not set

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\git\EncrypDecrypImage\En&deUI.py", line 73, in encrypt_decrypt_audio_file
    with wave.open(temp_file_path, 'wb') as wave_file:
  File "C:\Users\ypuku\AppData\Local\Programs\Python\Python312\Lib\wave.py", line 471, in __exit__
    self.close()
  File "C:\Users\ypuku\AppData\Local\Programs\Python\Python312\Lib\wave.py", line 583, in close
    self._ensure_header_written(0)
  File "C:\Users\ypuku\AppData\Local\Programs\Python\Python312\Lib\wave.py", line 601, in _ensure_header_written
    raise Error('# channels not specified')
wave.Error: # channels not specified
ERROR:root:Error caught: Error - sample width not specified
Traceback (most recent call last):
  File "d:\git\EncrypDecrypImage\En&deUI.py", line 76, in encrypt_decrypt_audio_file
    wave_file.setsampwidth(wave_file.getsampwidth())
                           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ypuku\AppData\Local\Programs\Python\Python312\Lib\wave.py", line 497, in getsampwidth
    raise Error('sample width not set')
wave.Error: sample width not set

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\git\EncrypDecrypImage\En&deUI.py", line 74, in encrypt_decrypt_audio_file
    with wave.open(temp_file_path, 'wb') as wave_file:
  File "C:\Users\ypuku\AppData\Local\Programs\Python\Python312\Lib\wave.py", line 471, in __exit__
    self.close()
  File "C:\Users\ypuku\AppData\Local\Programs\Python\Python312\Lib\wave.py", line 583, in close
    self._ensure_header_written(0)
  File "C:\Users\ypuku\AppData\Local\Programs\Python\Python312\Lib\wave.py", line 603, in _ensure_header_written
    raise Error('sample width not specified')
wave.Error: sample width not specified
ERROR:root:Error caught: Error - sample width not specified
Traceback (most recent call last):
  File "d:\git\EncrypDecrypImage\En&deUI.py", line 76, in encrypt_decrypt_audio_file
    wave_file.setsampwidth(wave_file.getsampwidth())
                           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ypuku\AppData\Local\Programs\Python\Python312\Lib\wave.py", line 497, in getsampwidth
    raise Error('sample width not set')
wave.Error: sample width not set

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\git\EncrypDecrypImage\En&deUI.py", line 74, in encrypt_decrypt_audio_file
    with wave.open(temp_file_path, 'wb') as wave_file:
  File "C:\Users\ypuku\AppData\Local\Programs\Python\Python312\Lib\wave.py", line 471, in __exit__
    self.close()
  File "C:\Users\ypuku\AppData\Local\Programs\Python\Python312\Lib\wave.py", line 583, in close
    self._ensure_header_written(0)
  File "C:\Users\ypuku\AppData\Local\Programs\Python\Python312\Lib\wave.py", line 603, in _ensure_header_written
    raise Error('sample width not specified')
wave.Error: sample width not specified
ERROR:root:Error caught: Error - sample width not specified
Traceback (most recent call last):
  File "d:\git\EncrypDecrypImage\En&deUI.py", line 76, in encrypt_decrypt_audio_file
    wave_file.setsampwidth(wave_file.getsampwidth())
                           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ypuku\AppData\Local\Programs\Python\Python312\Lib\wave.py", line 497, in getsampwidth
    raise Error('sample width not set')
wave.Error: sample width not set

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\git\EncrypDecrypImage\En&deUI.py", line 74, in encrypt_decrypt_audio_file
    with wave.open(temp_file_path, 'wb') as wave_file:
  File "C:\Users\ypuku\AppData\Local\Programs\Python\Python312\Lib\wave.py", line 471, in __exit__
    self.close()
  File "C:\Users\ypuku\AppData\Local\Programs\Python\Python312\Lib\wave.py", line 583, in close
    self._ensure_header_written(0)
  File "C:\Users\ypuku\AppData\Local\Programs\Python\Python312\Lib\wave.py", line 603, in _ensure_header_written
    raise Error('sample width not specified')
wave.Error: sample width not specified
